FILESEXTRAPATHS_prepend := "${THISDIR}/${PN}:"

SRC_URI += "file://no-incdefs-using-host-headers.patch"

EXTRA_OEMAKE = "ARCH=${TARGET_ARCH} \
    EXTRA_CFLAGS='-D_GNU_SOURCE -DHAVE_CLOCK_ADJTIME -DHAVE_POSIX_SPAWN -DHAVE_ONESTEP_SYNC ${CFLAGS}'"
